# Generated by Django 4.2 on 2025-04-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
