# Generated by Django 4.2 on 2025-04-17 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lesson', '0002_alter_level_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignLevels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
