# Generated by Django 4.2 on 2025-04-19 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lesson', '0003_assignlevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPaper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_answered', models.IntegerField(default=0)),
                ('answer_no', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
