# Generated by Django 4.2 on 2025-04-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0004_quizpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignlevels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizpaper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
